[prune]
  unused-packages = true
  go-tests = true
  non-go = true
    [[prune.project]]
      name = "github.com/hyperledger/burrow"
      unused-packages = false
      non-go = false

[[override]]
  name = "github.com/hyperledger/burrow"
  version = "=0.23.1"

[[override]]
  name = "github.com/tendermint/tendermint"
  version = "=0.24.0"

[[override]]
  name = "github.com/tendermint/go-amino"
  version = "^0.12.0-rc0"

#[[override]]
#  name = "github.com/gogo/protobuf"
#  version = "~1.1.0"
#
#[[override]]
#  name = "github.com/golang/protobuf"
#  version = "~1.1.0"
#
[[override]]
  name = "google.golang.org/grpc"
  version = "~1.13.0"

[[constraint]]
  name = "github.com/go-ozzo/ozzo-validation"
  version = "3.4.0"
