# Some reusable sections, note the top-level keys 'defaults' and 'tag_filters'
# have no special meaning, they just exist so I can alias them and import them
# in later blocks
defaults: &defaults
  working_directory: /go/src/github.com/monax/bosmarmot
  docker:
    - image: quay.io/monax/bosmarmot:ci

tag_filters: &tags_filters
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

setup_docker: &setup_docker
  version: 17.06.1-ce

# Start of CircleCI 2.0 config
version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: make npm_install
      - run: make test

  test_integration:
    working_directory: /go/src/github.com/monax/bosmarmot
    docker:
    - image: quay.io/monax/bosmarmot:ci
    - image: circleci/postgres:11-alpine-ram
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: vent

    steps:
      - checkout
      - run: make npm_install
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run: make test_integration

  ensure_vendor:
    <<: *defaults
    steps:
      - checkout
      - run: make ensure_vendor

  publish_npm:
    <<: *defaults
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
      - run: cd legacy-db.js && npm publish
      - run: cd legacy-contracts.js && npm publish

  publish_vent:
    working_directory: /go/src/github.com/monax/bosmarmot
    docker:
      - image: hyperledger/burrow:ci
    steps:
      - checkout
      - setup_remote_docker:
          <<: *setup_docker
      - run:
          name: Build vent image
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} quay.io
            docker build -t quay.io/monax/vent:$CIRCLE_BRANCH -f vent/Dockerfile .
            docker push quay.io/monax/vent:$CIRCLE_BRANCH


workflows:
  version: 2

  test_and_release:
    jobs:
      - test:
          filters:
            <<: *tags_filters

      - test_integration:
          filters:
            <<: *tags_filters

      - ensure_vendor:
          filters:
            <<: *tags_filters

      - publish_npm:
          requires:
            - test
            - test_integration
            - ensure_vendor
          filters:
            <<: *tags_filters
            branches:
              ignore: /.*/

      - publish_vent:
          requires:
            - test_integration
            - ensure_vendor
          filters:
            branches:
              only:
                - master
                - develop
